---
language: cpp

env:
  global:
    - MAKEFLAGS = "-j8"

matrix:
  include:
    - os: linux
      dist: focal
      compiler: gcc
    - os: osx
      compiler: clang
addons:
  apt:
    packages:
      - python3-dev
      - libxml2-dev
      - libfltk1.3-dev
      - fluid
      - libjpeg-dev
      - libglm-dev
      - libcminpack-dev
      - libglew-dev
      - swig
      - doxygen
      - graphviz
      - texlive-latex-base
  homebrew:
    update: true
    packages:
      - swig
      - gcc@9
      - llvm@7
script:
  - mkdir build buildlibs;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
     cd $TRAVIS_BUILD_DIR/buildlibs;
     cmake -DCMAKE_C_COMPILER=/usr/local/opt/llvm@7/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@7/bin/clang++ -DCMAKE_BUILD_TYPE=Release ../Libraries;
     make -j8;
     cd $TRAVIS_BUILD_DIR/build;
     cmake -DVSP_LIBRARY_PATH=$TRAVIS_BUILD_DIR/buildlibs -DCXX_OMP_COMPILER=/usr/local/bin/g++-9 -DC_OMP_COMPILER=/usr/local/bin/gcc-9 -DCMAKE_C_COMPILER=/usr/local/opt/llvm@7/bin/clang -DCMAKE_CXX_COMPILER=/usr/local/opt/llvm@7/bin/clang++ -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX="~/OpenVSP_Install" ../src;
     make -j8 package;
     ZIPFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS.zip;
     ls $ZIPFILE && (echo "ZIP CREATION SUCCESSFUL" && exit 0) || (echo "ZIP CREATION FAILED" && exit 1);
     export DEPLOY_FILE="$TRAVIS_BUILD_DIR/build/OpenVSP-*-MacOS.zip";
    fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
     cd $TRAVIS_BUILD_DIR/buildlibs;
     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_USE_SYSTEM_LIBXML2=true -DVSP_USE_SYSTEM_FLTK=true -DVSP_USE_SYSTEM_GLM=true -DVSP_USE_SYSTEM_GLEW=true -DVSP_USE_SYSTEM_CMINPACK=true -DVSP_USE_SYSTEM_CPPTEST=false ../Libraries;
     make -j8;
     cd $TRAVIS_BUILD_DIR/build;
     cmake -DCMAKE_BUILD_TYPE=Release -DVSP_CPACK_GEN=DEB -DVSP_LIBRARY_PATH=$TRAVIS_BUILD_DIR/buildlibs ../src;
     make -j8 package;
     DEBFILE=$TRAVIS_BUILD_DIR/build/OpenVSP-*-Linux.deb;
     ls $DEBFILE && (echo "DEB CREATION SUCCESSFUL" && exit 0) || (echo "DEB CREATION FAILED" && exit 1);
     export DEPLOY_FILE="$TRAVIS_BUILD_DIR/build/OpenVSP-*-Linux.deb";
    fi
deploy:
  provider: releases
  api_key:
    secure: YiWgUbqJ5w/wEq7hkUsbHnGMGZBAGVEZAGAMY97Hegn+lVY1MfgKRNMx79a2evW3aoRqFor/CQwbuA1+IrjnKt4XIwKHbIQysFTfQducRmIpbpRYz3yBA8jDFr/j9PmbZ1UD5rkKSYGbuBb0cYRLkEE+YJdUUBzgziH9g9kH7DwzVWCpHbm1NZKV9jQVRkSxrVj2jQupM1c1mcaeIvfUADLpUPW9fOBQTcS+4LNLuyVf+KlaoKUSCVi50g/9I1grfkWAilgvdPgOWE2vABnDcEgH82Vx2qRcoLMLWhCjH/6YbyzoqvpMNXflkXCpD///c/v575RIHEcjURJyWhzIayw+mawxwoaXrSMVrJgPtyRAtEMuACye/QjUbwS9qDPXAXYMy/kdggOAL4YVDwaD+Cmu9+5shwEBFEUyXOoYubMLkeKQjeUDhgG6l06kLMf6QyYSPv3w2LZxzdZs1wS3e2A5L7JYOzLUo+NbGzzkItby+yJrAXAbd7ECtACu+DqVrJKPS0dFXkBpXn7rHG0p2FXPEcNBv7YwquKnUnIcy42n+5qTu7LR4tS5kQ/LuoeuN4YIZ6YZVUbQQEwtEDpRW/IVBQ9f76U5C+xjFYOUL/3nrQV7onjUlhNwDzQUxSRGE3dhzmia3deYN51YLfrWiudo7X7bB3Ik/m5q+22Ylys=
  draft: true
  file_glob: true
  name: "$TRAVIS_COMMIT Draft Deployment"
  file: $DEPLOY_FILE
  skip_cleanup: true
  on:
    all_branches: true
